### ISSUE TITLE
Maybe my camera is not supported, error upon running the script WindowsTouch.py

### ISSUE THREAD

**Issue by MagedEWilliam** [ashishgupta1350/Windows-Touch#3]
This is basically what happens upon running the script:

![the issue](
https://drive.google.com/uc?export=view&id=1RNOzSOx05geisC_DXWk0xZH48ptXIFK_)

```
Traceback (most recent call last):
  File "WindowsTouch.py", line 397, in <module>
    main()
  File "WindowsTouch.py", line 383, in main
    if not currStage(segmented, debugframe, options, ticks, drawframe, calib, state):
  File "WindowsTouch.py", line 223, in _calibration
    x, y, touch = find(segmented, debugframe=drawframe, options=options)
  File "WindowsTouch.py", line 152, in find
    _, cnts, _ = cv2.findContours(segmented_image.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)
[ WARN:0] terminating async callback
```

**Comment by CaozyDev** [comment]
Me too.
![image](https://github.com/ashishgupta1350/Windows-Touch/assets/98444138/ad3c5634-d4ca-4a55-a746-600dbd0f66c1)
